## Results

This document provides the results of the manuscript "Preference disaggregation on TOPSIS for sorting applied to an economic freedom assessment".

The data is organized in lists:

- Original_Classification: Heritage classifications for the different years
- Total_Classification: classifications obtained for the alternatives in the simulations
- Total_References: reference alternatives used for each simulation
- Total_Cl: closeness coefficients of the alternatives for each simulation
  
The indexes are:
    
- n_methods=2 # Number of methods   
    - [0] for POTOPSIS-Sort-B
    - [1] for PDTOPSIS-Sort-C
    
- n_refcomb=5 # Number of sizes of reference combinations
    - [0] -> 1 exemplo de decisão por classe
    - [1] -> 2 exemplo de decisão por classe
    - [2] -> 3 exemplo de decisão por classe
    - [3] -> 4 exemplo de decisão por classe
    - [4] -> 5 exemplo de decisão por classe

- n_years=4 # Number of years
    - [0] para 2017
    - [1] para 2018
    - [2] para 2019
    - [3] para2020

- n_sim=100 #Number of simulations
    - The index varies between [0] and [99]


The lists have been created using the index as below:
    
- Total_Classification=[[[[[] for d in range (n_methods)] for c in range (n_years)] for b in range (n_refcomb)] for a in range (n_sim)]
- Total_References=[[[[] for x in range (n_years)] for y in range (n_refcomb)] for z in range (n_sim)]
- Total_Cl=[[[[[] for d in range (n_methods)] for c in range (n_years)] for b in range (n_refcomb)] for a in range (n_sim)]


To acess a specific table:
    
- Original_Classification[year_index]
- Total_Classification[simulation_index][refcomb_index][year_index][method_index]
- Total_References[simulation_index][refcomb_index][year_index]
- Total_Cl[simulation_index][refcomb_index][year_index][method_index]

### Extracting data

The data is provided as a spydata file and can be read with the cell below.

In [19]:
import pickle
import tarfile
filename = 'data_manuscript.spydata'
tar = tarfile.open(filename, "r")
tar.extractall()
extracted_files = tar.getnames()
for f in extracted_files:
    if f.endswith('.pickle'):
         with open(f, 'rb') as fdesc:
             data = pickle.loads(fdesc.read())
locals().update(data)

### Accessing a specific result

Lets acess the classification obtained by PDTOPSI-Sort-C in a specific simulation.

- [81] -> simulation number 80
- [2] -> 3 references per class
- [3] -> year 2019 
- [1] -> PDTOPSIS-Sorc-C

In [20]:
Total_Classification[81][2][3][1]

Name
Afghanistan    5
Albania        3
Algeria        5
Angola         5
Argentina      5
              ..
Vanuatu        3
Venezuela      5
Vietnam        4
Zambia         4
Zimbabwe       5
Name: Class, Length: 180, dtype: int64

The 15 references used in this case were:

In [21]:
Total_References[81][2][3]

,Property Rights,Judicial Effectiveness,Government Integrity,Tax Burden,Government Spending,Fiscal Health,Business Freedom,Labor Freedom,Monetary Freedom,Trade Freedom,Investment Freedom,Financial Freedom,Category
Name,,,,,,,,,,,,,
Ireland,86.6,64.4,82.8,76.4,78.8,91.4,82.7,75.9,85.3,86.4,90.0,70.0,1
Australia,82.8,86.1,89.3,63.0,61.6,91.8,87.8,84.0,86.2,88.2,80.0,90.0,1
Singapore,96.8,92.9,92.4,90.3,91.1,80.0,92.8,90.9,85.6,94.8,85.0,80.0,1
Malaysia,86.5,74.6,49.4,85.7,84.6,80.2,87.8,74.5,81.6,82.0,60.0,50.0,2
Estonia,83.2,73.7,85.9,81.1,53.3,99.9,73.5,57.3,78.6,86.4,90.0,70.0,2
Latvia,72.3,51.1,46.4,76.9,58.3,96.5,77.0,72.4,80.2,86.4,85.0,60.0,2
Belarus,63.2,48.4,37.4,88.8,54.1,95.4,76.4,74.8,69.8,82.0,30.0,20.0,3
Kosovo,66.3,54.1,39.2,92.6,76.5,94.0,75.0,61.0,78.4,76.2,65.0,30.0,3
Colombia,61.1,32.8,46.1,70.4,77.0,85.5,71.3,78.0,77.5,81.2,80.0,70.0,3
Solomon Islands,54.6,53.7,33.5,65.6,34.2,76.6,67.7,72.0,84.3,48.0,15.0,30.0,4
South Africa,58.4,38.0,46.6,63.7,67.4,64.0,62.0,58.8,75.9,75.8,45.0,50.0,4
Senegal,52.4,39.8,40.6,70.2,84.4,75.2,50.4,38.1,79.7,65.4,60.0,40.0,4
Democratic Republic of Congo,30.1,26.5,13.1,74.4,95.4,98.0,51.2,41.6,49.6,64.6,30.0,20.0,5
Sierra Leone,40.7,39.4,21.8,87.5,83.5,9.8,50.1,29.7,64.2,69.4,60.0,20.0,5
Turkmenistan,20.1,20.0,21.4,95.9,93.1,94.5,30.0,20.0,68.7,74.2,10.0,10.0,5

The classification for PDTOPSIS-Sort-B could be accessed in:

In [22]:
Total_Classification[81][2][3][0]

Name
Afghanistan    5
Albania        3
Algeria        5
Angola         5
Argentina      5
              ..
Vanuatu        3
Venezuela      5
Vietnam        4
Zambia         4
Zimbabwe       5
Name: Class, Length: 180, dtype: int64